export const mockUsers = [
    { id: 1, username: 'Anson', displayName: 'Anson', password: 'Anson123' },
    { id: 2, username: 'Jack', displayName: 'Jack', password: 'Jack123' },
    { id: 3, username: 'Duy', displayName: 'Duy', password: 'Duy123' },
    { id: 4, username: 'Mia', displayName: 'Mia', password: 'Mia123' },
    { id: 5, username: 'Liam', displayName: 'Liam', password: 'Liam123' },
    { id: 6, username: 'Emma', displayName: 'Emma', password: 'Emma123' },
    { id: 7, username: 'Noah', displayName: 'Noah', password: 'Noah123' },
    { id: 8, username: 'Sophia', displayName: 'Sophia', password: 'Sophia123' },
    { id: 9, username: 'Olivia', displayName: 'Olivia', password: 'Olivia123' },
    { id: 10, username: 'Lucas', displayName: 'Lucas', password: 'Lucas123' },
    { id: 11, username: 'Ethan', displayName: 'Ethan', password: 'Ethan123' },
    { id: 12, username: 'Ava', displayName: 'Ava', password: 'Ava123' },
    { id: 13, username: 'Harper', displayName: 'Harper', password: 'Harper123' },
]
